"""Pydantic schemas for the email-writer agent."""

from pydantic import BaseModel, EmailStr, Field


class EmailContent(BaseModel):
    """LLM-generated email content.

    The agent produces only the subject and body. The from/to addresses
    are chosen by the user and are NOT generated by the agent.
    """

    subject: str = Field(
        ...,
        min_length=1,
        description="The email subject line.",
    )
    body: str = Field(
        ...,
        min_length=1,
        description="The full email body.",
    )


class Email(BaseModel):
    """Complete email ready to be sent.

    Combines the LLM-generated content (subject, body) with the
    user-chosen sender and recipient addresses.
    """

    from_email: EmailStr = Field(
        ...,
        description="Sender email address chosen by the user.",
    )
    to_email: EmailStr = Field(
        ...,
        description="Recipient email address chosen by the user.",
    )
    email_body: EmailContent = Field(
        ...,
        description="The email body includes subject and body field.",
    )
